# INRTODUCTION/OVERVIEW

In [86]:
import pandas as pd
import ast
from sklearn.feature_extraction.text import TfidfVectorizer as tfv
from sklearn.metrics.pairwise import cosine_similarity as cs
import joblib

In [67]:
df = pd.read_csv("tmdbcredits.csv", engine='python', on_bad_lines='skip')
dff = pd.read_csv("tmdbmovies.csv")
dff.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [68]:
df.tail()

,movie_id,title,cast,crew
349,116745,The Secret Life of Walter Mitty,"[{""cast_id"": 11, ""character"": ""Walter Mitty"", ...","[{""credit_id"": ""52fe4b9dc3a36847f820c10b"", ""de..."
350,4327,Charlie's Angels,"[{""cast_id"": 1, ""character"": ""Natalie Cook"", ""...","[{""credit_id"": ""52fe43bac3a36847f806b227"", ""de..."
351,1422,The Departed,"[{""cast_id"": 2, ""character"": ""William \""Billy\...","[{""credit_id"": ""52fe42f5c3a36847f802fed5"", ""de..."
352,10674,Mulan,"[{""cast_id"": 10, ""character"": ""Mushu (voice)"",...","[{""credit_id"": ""52fe43a09251416c75017cc7"", ""de..."
353,7446,Tropic Thunder,"[{""cast_id"": 2, ""character"": ""Tugg Speedman"", ...","[{""credit_id"": ""52fe447dc3a36847f8099323"", ""de..."

In [69]:
dff.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [70]:
df.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [71]:

dff["release_date"] = pd.to_datetime(dff["release_date"])
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   datetime64[ns]
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(4), object(12)
memory usage: 750.6+ KB

In [72]:
tag = dff[["title","genres","overview","keywords","tagline"]]
tag.tail()

,title,genres,overview,keywords,tagline
4798,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","He didn't come looking for trouble, but troubl..."
4799,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,[],A newlywed couple's honeymoon is upended by th...
4800,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",NaN
4801,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,[],A New Yorker in Shanghai
4802,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",NaN

In [73]:
df = df["cast"]
df.head()

0    [{"cast_id": 242, "character": "Jake Sully", "...
1    [{"cast_id": 4, "character": "Captain Jack Spa...
2    [{"cast_id": 1, "character": "James Bond", "cr...
3    [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4    [{"cast_id": 5, "character": "John Carter", "c...
Name: cast, dtype: object

# FEATURE SELECTION

In [74]:
tag = pd.concat([tag,df],axis=1)
tag.tail()

,title,genres,overview,keywords,tagline,cast
4798,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","He didn't come looking for trouble, but troubl...",NaN
4799,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,[],A newlywed couple's honeymoon is upended by th...,NaN
4800,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",NaN,NaN
4801,Shanghai Calling,[],When ambitious New York attorney Sam is sent t...,[],A New Yorker in Shanghai,NaN
4802,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",NaN,NaN

# Columns like "genres", "keywords" and "cast" are in JSON-like structure we need to extrect them to normal/plain text

In [75]:
tag.dropna(inplace=True)
tag.reset_index(drop=True, inplace=True)
tag.isnull().sum()

title       0
genres      0
overview    0
keywords    0
tagline     0
cast        0
dtype: int64

# JSON Extraction

In [76]:
def extract_names(text):

    names = []

    for item in ast.literal_eval(text):
        names.append(item["name"])

    return " ".join(names)

In [77]:
tag["genres"] = tag["genres"].apply(extract_names)
tag["keywords"] = tag["keywords"].apply(extract_names)
tag["cast"] = tag["cast"].apply(extract_names)

# Now we have just converted JSON-like structure to plain text with above code ready for Vectorization

In [78]:
tag.head()

,title,genres,overview,keywords,tagline,cast
0,Avatar,Action Adventure Fantasy Science Fiction,"In the 22nd century, a paraplegic Marine is di...",culture clash future space war space colony so...,Enter the World of Pandora.,Sam Worthington Zoe Saldana Sigourney Weaver S...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,"Captain Barbossa, long believed to be dead, ha...",ocean drug abuse exotic island east india trad...,"At the end of the world, the adventure begins.",Johnny Depp Orlando Bloom Keira Knightley Stel...
2,Spectre,Action Adventure Crime,A cryptic message from Bond’s past sends him o...,spy based on novel secret agent sequel mi6 bri...,A Plan No One Escapes,Daniel Craig Christoph Waltz Léa Seydoux Ralph...
3,The Dark Knight Rises,Action Crime Drama Thriller,Following the death of District Attorney Harve...,dc comics crime fighter terrorist secret ident...,The Legend Ends,Christian Bale Michael Caine Gary Oldman Anne ...
4,John Carter,Action Adventure Science Fiction,"John Carter is a war-weary, former military ca...",based on novel mars medallion space travel pri...,"Lost in our world, found in another.",Taylor Kitsch Lynn Collins Samantha Morton Wil...

# So now how do i measure similarity between Movies? By converting text to numbers(vectors) using Vectorization

# Our exact work here is called "Content-based filtering"

Now before Vectoriation we need to combine all useful features into ONE (FEATURE ENGINEERING)

Why because TF-IDF works best on a single text field.

# FEATURE ENGINEERING and TEXT COMBINATION

In [79]:
tag["tags"] = (
   tag["cast"] + " " +
    tag["genres"] + " " +
    tag["overview"] + " " +
    tag["keywords"]
)
tag.tail()

,title,genres,overview,keywords,tagline,cast,tags
340,The Secret Life of Walter Mitty,Adventure Comedy Drama Fantasy,A timid magazine photo manager who lives life ...,himalaya photographer magazine iceland daydrea...,"Stop Dreaming, Start Living",Ben Stiller Kristen Wiig Patton Oswalt Shirley...,Ben Stiller Kristen Wiig Patton Oswalt Shirley...
341,Charlie's Angels,Action Adventure Comedy Crime Thriller,Aspects of this take on the 1970s hit TV serie...,martial arts female friendship millionaire agent,Get Some Action,Cameron Diaz Lucy Liu Drew Barrymore Bill Murr...,Cameron Diaz Lucy Liu Drew Barrymore Bill Murr...
342,The Departed,Drama Thriller Crime,"To take down South Boston's Irish Mafia, the p...",undercover boston police friends mafia underco...,Lies. Betrayal. Sacrifice. How far will you ta...,Leonardo DiCaprio Matt Damon Jack Nicholson Ma...,Leonardo DiCaprio Matt Damon Jack Nicholson Ma...
343,Mulan,Animation Family Adventure,A tomboyish girl disguises herself as a young ...,homeland musical training daughter cricket pri...,"This time, the princess saves the prince.",Eddie Murphy Jackie Chan Ming-Na Wen Lea Salon...,Eddie Murphy Jackie Chan Ming-Na Wen Lea Salon...
344,Tropic Thunder,Action Comedy,"Vietnam veteran 'Four Leaf' Tayback's memoir, ...",film making satire jungle movie star southeast...,The movie they think they're making... isn't a...,Ben Stiller Jack Black Robert Downey Jr. Nick ...,Ben Stiller Jack Black Robert Downey Jr. Nick ...

# TF-IDF Vectorization

In [80]:
vector = tfv(stop_words="english")
vector_matrix = vector.fit_transform(tag["tags"])

# COSINE SIMILARITY

In [81]:
similarity = cs(vector_matrix)
similarity

array([[1.        , 0.01925684, 0.01434406, ..., 0.04285754, 0.01144676,
        0.06038278],
       [0.01925684, 1.        , 0.01501273, ..., 0.03766812, 0.00884726,
        0.0262147 ],
       [0.01434406, 0.01501273, 1.        , ..., 0.01489105, 0.00807123,
        0.00859671],
       ...,
       [0.04285754, 0.03766812, 0.01489105, ..., 1.        , 0.02061728,
        0.03522244],
       [0.01144676, 0.00884726, 0.00807123, ..., 0.02061728, 1.        ,
        0.00462466],
       [0.06038278, 0.0262147 , 0.00859671, ..., 0.03522244, 0.00462466,
        1.        ]])

# RECOMMENDATION FUNCTION

In [82]:
def recommend(movie_name):

    movie_index = tag[tag["title"] == movie_name].index[0]

    distances = similarity[movie_index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]  # top 5 (excluding itself)

    for i in movie_list:
        print(tag.iloc[i[0]].title)

# TESTING RECOMMENDTIONS

In [85]:
recommend("Avatar")

Star Trek Into Darkness
Treasure Planet
Planet of the Apes
Armageddon
Home

In [87]:
joblib.dump(tag, "movies.pkl")
joblib.dump(similarity, "similarity.pkl")

['similarity.pkl']

# FINDINGS
- TF-IDF combined some important features together because vectorizer can only use one text column rather than two/more
- Cosine Similarity is then used to find similarities between movies categories mathematically before the creation of "recommendation function" that gives us the actual recommendation we need after inputting any movie name.

# CONCLUSION
JSON-like structure was transformed to plain text for effective vectorization. Recommendation system performs accurately(giving us 5 similar movies which was set to default) in recommending related movie content